export const COUNTRY_PHONE_CODES = [
  { code: '+1', country: 'US', label: 'United States (+1)' },
  { code: '+1', country: 'CA', label: 'Canada (+1)' },
  { code: '+44', country: 'GB', label: 'United Kingdom (+44)' },
  { code: '+61', country: 'AU', label: 'Australia (+61)' },
  { code: '+62', country: 'ID', label: 'Indonesia (+62)' },
  { code: '+63', country: 'PH', label: 'Philippines (+63)' },
  { code: '+65', country: 'SG', label: 'Singapore (+65)' },
  { code: '+66', country: 'TH', label: 'Thailand (+66)' },
  { code: '+81', country: 'JP', label: 'Japan (+81)' },
  { code: '+82', country: 'KR', label: 'South Korea (+82)' },
  { code: '+84', country: 'VN', label: 'Vietnam (+84)' },
  { code: '+86', country: 'CN', label: 'China (+86)' },
  { code: '+90', country: 'TR', label: 'Turkey (+90)' },
  { code: '+91', country: 'IN', label: 'India (+91)' },
  { code: '+234', country: 'NG', label: 'Nigeria (+234)' },
  { code: '+49', country: 'DE', label: 'Germany (+49)' },
  { code: '+33', country: 'FR', label: 'France (+33)' },
  { code: '+39', country: 'IT', label: 'Italy (+39)' },
  { code: '+34', country: 'ES', label: 'Spain (+34)' },
  { code: '+55', country: 'BR', label: 'Brazil (+55)' },
  { code: '+52', country: 'MX', label: 'Mexico (+52)' },
  { code: '+7', country: 'RU', label: 'Russia (+7)' },
  { code: '+27', country: 'ZA', label: 'South Africa (+27)' },
  { code: '+971', country: 'AE', label: 'UAE (+971)' },
  { code: '+966', country: 'SA', label: 'Saudi Arabia (+966)' },
  { code: '+60', country: 'MY', label: 'Malaysia (+60)' },
  { code: '+880', country: 'BD', label: 'Bangladesh (+880)' },
  { code: '+92', country: 'PK', label: 'Pakistan (+92)' },
  { code: '+20', country: 'EG', label: 'Egypt (+20)' },
  { code: '+254', country: 'KE', label: 'Kenya (+254)' },
];

export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Argentina', 'Australia', 'Austria',
  'Bangladesh', 'Belgium', 'Brazil', 'Cambodia', 'Canada', 'Chile', 'China',
  'Colombia', 'Czech Republic', 'Denmark', 'Egypt', 'Finland', 'France',
  'Germany', 'Ghana', 'Greece', 'Hungary', 'India', 'Indonesia', 'Iran',
  'Iraq', 'Ireland', 'Israel', 'Italy', 'Japan', 'Jordan', 'Kenya',
  'Malaysia', 'Mexico', 'Morocco', 'Myanmar', 'Nepal', 'Netherlands',
  'New Zealand', 'Nigeria', 'Norway', 'Pakistan', 'Peru', 'Philippines',
  'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Saudi Arabia',
  'Singapore', 'South Africa', 'South Korea', 'Spain', 'Sri Lanka',
  'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'UAE',
  'Uganda', 'Ukraine', 'United Kingdom', 'United States', 'Vietnam'
];
